project/website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "thongfaa love mass"

    from .views import views

    app.register_blueprint(views, url_prefix = '/')

    return app

project/website/views.py
# views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
import random
import re  # Import the regular expression module for password strength check

views = Blueprint("views", __name__)

def generate_password(num_passwords, pwlength, categories, keyword=None, keyword_position=None):
    alphabet = ''
    if categories.get('text', False):
        alphabet += 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    if categories.get('number', False):
        alphabet += '0123456789'
    if categories.get('special', False):
        alphabet += '!@#$%^&*()_+-=[]{}|;:,.<>?/'

    # If none of the categories are selected, include all of them by default
    if not any(categories.values()):
        alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-=[]{}|;:,.<>?/'

    passwords = []

    for _ in range(num_passwords):
        remaining_length = pwlength

        if keyword:
            remaining_length -= len(keyword)
        
        if remaining_length <= 0:
            password = keyword if keyword else ''
        else:
            random_chars = ''.join(random.choice(alphabet) for _ in range(remaining_length))

            if keyword and keyword_position:
                if keyword_position == 'front':
                    password = keyword + random_chars
                elif keyword_position == 'behind':
                    password = random_chars + keyword
                elif keyword_position == 'between':
                    index = random.randrange(remaining_length)
                    password = random_chars[:index] + keyword + random_chars[index:]
                else:
                    raise ValueError("Invalid keyword position")
            else:
                password = random_chars

        passwords.append(password)

    return passwords

def check_password_strength(password):
    # Define criteria for a strong password
    length_criteria = 8
    uppercase_criteria = r'[A-Z]'
    lowercase_criteria = r'[a-z]'
    number_criteria = r'\d'
    special_char_criteria = r'[!@#$%^&*()_+-=[]{}|;:,.<>?/]'

    # Check length
    if len(password) < length_criteria:
        return "Weak: Password should be at least {} characters long.".format(length_criteria)

    # Check uppercase letters
    if not re.search(uppercase_criteria, password):
        return "Weak: Password should contain at least one uppercase letter."

    # Check lowercase letters
    if not re.search(lowercase_criteria, password):
        return "Weak: Password should contain at least one lowercase letter."

    # Check numbers
    if not re.search(number_criteria, password):
        return "Weak: Password should contain at least one number."

    # Check special characters
    if not re.search(special_char_criteria, password):
        return "Weak: Password should contain at least one special character."

    # If all criteria are met, consider the password strong
    return "Strong: Password meets all criteria."

@views.route("/", methods=["GET", "POST"])
def genpass():
    if request.method == "POST":
        pwnums = request.form.get("pwnums")
        pwlength = request.form.get("pwlength")
        keyword = request.form.get("keyword")
        keyword_position = request.form.get("keyword_position")

        include_text = request.form.get("text") == "on"
        include_number = request.form.get("number") == "on"
        include_special = request.form.get("special") == "on"

        # Include all character sets by default if none are selected
        if not any([include_text, include_number, include_special]):
            include_text = include_number = include_special = True

        if not pwnums or not pwlength:
            flash("Please fill out all required fields.", category="error")
        elif not pwnums.isdigit() or not pwlength.isdigit():
            flash("Please enter valid positive integers for Numbers of Passwords and Password Length.", category="error")
        elif int(pwlength) <= 0 or int(pwnums) <= 0:
            flash("Please enter valid positive integers for Numbers of Passwords and Password Length.", category="error")
        else:
            flash("Passwords generated", category="success")

            categories = {
                'text': include_text,
                'number': include_number,
                'special': include_special,
            }

            passwords = generate_password(int(pwnums), int(pwlength), categories, keyword, keyword_position)

            # Check the strength of each password
            strength_messages = [check_password_strength(password) for password in passwords]

            return render_template('generatedpw.html', passwords=passwords, strength_messages=strength_messages)

    return render_template("genpass.html")

# Check Strongest Password

def find_strongest_password(passwords):
    strongest_password = None
    max_special_count = 0
    strongest_strength = "Weak: No strong passwords found."

    for password in passwords:
        strength = check_password_strength(password)
        special_count = sum(1 for char in password if char in "!@#$%^&*()_+-=[]{}|;:,.<>?/")
        
        if "Strong" in strength and (strongest_password is None or special_count > max_special_count):
            strongest_password = password
            max_special_count = special_count
            strongest_strength = strength

    return strongest_password, strongest_strength

# ...

project/website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale = 1" />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />

        <title>{% block title %}Generate Password{% endblock %}</title>
    </head>
    <body>
        {% with messages = get_flashed_messages(with_categories = true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == "error" %}
            <div class="alert alert-danger alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">   
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">   
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

project/website/templates/generatedpw.html
{% extends "base.html" %}
{% block title %}Generated Passwords{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <h3 class="mb-4">Generated Passwords</h3>

            {% for i in range(5) %}
                {% if i < passwords|length %}
                    <div class="row mb-3">
                        <div class="col-8">
                            <input type="text" class="form-control mb-2" value="{{ passwords[i] }}" readonly>
                        </div>
                        <div class="col-4">
                            <button type="button" class="btn btn-outline-primary btn-block minimal-btn" onclick="copyToClipboard('{{ passwords[i] }}')">Copy</button>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            {% if passwords|length > 5 %}
                <div class="row mb-3">
                    <div class="col-2">
                        <button type="button" class="btn btn-secondary btn-block minimal-btn" id="showHidePasswordsBtn" onclick="togglePasswordsVisibility()">Show All</button>
                    </div>
                    <div class="col-2">
                        <a href="{{ url_for('views.genpass') }}" class="btn btn-secondary btn-block minimal-btn">Back</a>
                    </div>
                </div>
                <div id="hiddenPasswords" style="display: none;">
                    {% for i in range(5, passwords|length) %}
                        <div class="row mb-3">
                            <div class="col-8">
                                <input type="text" class="form-control mb-2" value="{{ passwords[i] }}" readonly>
                            </div>
                            <div class="col-4">
                                <button type="button" class="btn btn-outline-primary btn-block minimal-btn" onclick="copyToClipboard('{{ passwords[i] }}')">Copy</button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="row mb-3">
                    <div class="col-2">
                        <a href="{{ url_for('views.genpass') }}" class="btn btn-secondary btn-block minimal-btn">Back</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<script>
    function copyToClipboard(text) {
        var textarea = document.createElement("textarea");
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        alert('Password copied to clipboard!');
    }

    function togglePasswordsVisibility() {
        var hiddenPasswordsDiv = document.getElementById('hiddenPasswords');
        var showHidePasswordsBtn = document.getElementById('showHidePasswordsBtn');

        if (hiddenPasswordsDiv.style.display === 'none') {
            hiddenPasswordsDiv.style.display = 'block';
            showHidePasswordsBtn.textContent = 'Hide';
        } else {
            hiddenPasswordsDiv.style.display = 'none';
            showHidePasswordsBtn.textContent = 'Show All';
        }
    }
</script>


{% endblock %}

project/website/templates/genpass.html
{% extends "base.html" %}
{% block title %}Generate Password{% endblock %}

{% block content %}
<form method="POST">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h3 class="text-center mb-4">Generate Password</h3>

                <div class="form-group">
                    <label for="pwnums">Numbers of Passwords</label>
                    <input type="number" class="form-control" id="pwnums" name="pwnums" placeholder="Enter number of passwords">
                </div>

                <div class="form-group">
                    <label for="pwlength">Password Length</label>
                    <input type="number" class="form-control" id="pwlength" name="pwlength" placeholder="Enter password length">
                </div>

                <div class="form-row">
                    <div class="form-group col-md-7">
                        <label for="keyword">Keyword</label>
                        <input type="text" class="form-control" id="keyword" name="keyword" placeholder="Enter keyword">
                    </div>

                    <div class="form-group col-md-5">
                        <label for="keyword_position">Keyword Position</label>
                        <select class="form-control" id="keyword_position" name="keyword_position">
                            <option value="front">Front</option>
                            <option value="behind">Behind</option>
                            <option value="between">Between</option>
                        </select>
                    </div>
                </div>

                <div class="form-check form-check-inline">
                    <input type="checkbox" class="form-check-input" id="text" name="text">
                    <label class="form-check-label" for="text">Include Text</label>
                </div>

                <div class="form-check form-check-inline">
                    <input type="checkbox" class="form-check-input" id="number" name="number">
                    <label class="form-check-label" for="number">Include Number</label>
                </div>

                <div class="form-check form-check-inline">
                    <input type="checkbox" class="form-check-input" id="special" name="special">
                    <label class="form-check-label" for="special">Include Special Character</label>
                </div>

                <div class="mt-4" align="center">
                    <button type="submit" class="btn btn-primary">Generate Passwords</button>
                    <button type="reset" class="btn btn-secondary">Clear</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}